### ISSUE TITLE
Bug in calculating Euclidean distance

### ISSUE THREAD

**Issue by jadelonghans** [j2kun/earthmover#1]
In the function, euclidean_distance(x, y), shouldn't the sum be square-rooted before return? i guess that's the distance formula?

As in:
```
def euclidean_distance(x, y):
    return math.sqrt(sum((a - b)**2 for (a, b) in zip(x, y)))
```

**Comment by j2kun** [comment]
You're right. I think I am able to do an optimization here by minimizing the sum-of-squares (i.e., if you minimize the sum of squares you also minimize its square root), but I'm not so sure any more that this is a valid optimization...

**Comment by jadelonghans** [comment]
I am not sure if I follow you. 

We are only using Euclidean dist for calculating work (EMD).
And we're using the Linear Solver to find minimum EMD by solving the corresponding optimization problem.
Why would not that be a valid optimization? (assuming we're simply minimizing the square root, and not sum of squares)

Kindly explain.
