### ISSUE TITLE
Prints 0.0

### ISSUE THREAD

**Issue by gocen** [j2kun/earthmover#2]
Thank you for sharing this code.
I downloaded and run earthmover.py
But it just outputs 0.0 even changing the values

**Comment by j2kun** [comment]
You are probably using Python 2, which uses integer division.

Note that Python 2 will reach the end of its life on January 1st, 2020. I recommend you upgrade to python3.7.

Nevertheless, I have modified the code to support with python2. It should work fine now.

**Comment by gocen** [comment]
Now it works, thank you. My editor geany supports python2 so I use it.
I have one more question. Is it possible to using your code for computing 2D matrix distance with same size.
Or, Do you advice any other code?
